name: cloudns登录

on:
  schedule:
    # 每天凌晨 2 点运行（UTC 时间）
    - cron: '0 2 */5 * *'
  workflow_dispatch:  # 允许手动触发

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run main script
        env:
          CLOUDNS_API_ID: ${{ secrets.CLOUDNS_API_ID }}
          CLOUDNS_API_PASSWORD: ${{ secrets.CLOUDNS_API_PASSWORD }}
          QMSG_KEY: ${{ secrets.QMSG_KEY }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          EMAIL: ${{ secrets.EMAIL }}  # 引用 GitHub Secrets 中的 EMAIL
          DESEC: ${{ secrets.DESEC }}  # 引用 GitHub Secrets 中的 DESEC
        run: |
          python cloudns.py
