name: DK

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '9 5 1,7,13,19,25 * *'
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: 初始化Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: 安装依赖
        run: |
          pip install requests
  
      - name: 53
        run: |
          python3 dk.py
          

