name: gv

on:
  push:
    branches:
      - main  # 触发条件：推送到 main 分支时运行
  pull_request:
    branches:
      - main  # 触发条件：创建 pull request 到 main 分支时运行
  workflow_dispatch:  # 手动触发
  schedule:
    - cron: '3 21 * * *'  # 每天UTC时间21:03运行

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # 如果存在requirements.txt
        env:
          GV_URL: ${{ secrets.GV_URL }}
      
      - name: Run script
        run: |
          # 创建result目录（如果不存在)
          python gv.py  # 确保脚本输出到result目录
      
      - name: cs
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add results/
          git commit -m "Auto update speedtest results" || echo "No changes to commit"
          git push
