name: 

on:
  workflow_dispatch:  # 手动触发
  schedule:
    - cron: '3 21 * * *'  # 每6小时自动运行

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - run: pip install requests -r requirements.txt
        env:
          GV_URL: ${{ secrets.GV_URL }}
      
      - run: python gv.py
      
      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add gg.txt
          git commit -m "自动更新加密节点列表 $(date +'%Y-%m-%d %H:%M')" || echo "无变更"
          git push