name: gv

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '3 21 * * *'  # 每天UTC时间21:03运行jobs:
  update:
    runs-on: ubuntu-latest
    env:
      GVURL: ${{ secrets.GVURL }}  # 全局变量
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Debug env
        run: echo "GVURL值: $GVURL"  # 验证变量

      - name: Run script
        run: |
          mkdir -p results
          python gv.py

      - name: Commit changes
        if: success()
        run: |
          git add results/
          git commit -m "Auto update $(date +'%Y-%m-%d')" || echo "No changes"
          git push