name: Node Speed Test

on:
  workflow_dispatch:  # 手动触发
  schedule:
    - cron: '0 18 * * *'  # 每天UTC时间18点运行

jobs:
  speedtest:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: pip install requests
    
    - name: Run speed test
      run: python vt.py
    
    - name: Commit results
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add results/
        git commit -m "Auto update speedtest results" || echo "No changes to commit"
        git push